# Generated by Django 2.1.3 on 2018-11-29 19:19

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_document_file_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='activitycollection',
            name='accesscode',
            field=models.CharField(max_length=255, null=True, unique=True, validators=[django.core.validators.MinLengthValidator(10)], verbose_name='Access Code'),
        ),
        migrations.AlterField(
            model_name='activitycollection',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='activitycollection',
            name='is_public',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='document',
            name='file_upload',
            field=models.FileField(blank=True, null=True, upload_to='documents'),
        ),
        migrations.AlterField(
            model_name='post',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
