# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-05 20:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='attachment',
            name='document_ptr',
        ),
        migrations.RemoveField(
            model_name='attachment',
            name='flatpage',
        ),
        migrations.DeleteModel(
            name='Attachment',
        ),
    ]
