# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 02:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        ('flatpage', '0004_auto_20161206_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpageactivity',
            name='attachments',
            field=models.ManyToManyField(blank=True, null=True, to='core.Document'),
        ),
    ]
