# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 23:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage', '0005_flatpageactivity_attachments'),
    ]

    operations = [
        migrations.AddField(
            model_name='flatpageactivity',
            name='slug',
            field=models.SlugField(allow_unicode=True, default='', unique=True),
        ),
    ]
