# Generated by Django 2.1.3 on 2018-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('flatpage', '0008_remove_flatpageactivity_attachments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='flatpageactivity',
            name='activity_type',
            field=models.CharField(choices=[('discussion', 'Discussion Activity'), ('essay', 'Essay Activity'), ('overdub', 'Overdub Media Activity'), ('flatpage', 'Flatpage Activity')], default='discussion', max_length=100),
        ),
        migrations.AlterField(
            model_name='flatpageactivity',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='flatpageactivity',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='core.Lesson'),
        ),
        migrations.AlterField(
            model_name='flatpageactivity',
            name='posts',
            field=models.ManyToManyField(blank=True, to='core.Post'),
        ),
    ]
