# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 00:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='DiscussionActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[(b'discussion', b'Discussion Activity'), (b'essay', b'Essay Activity'), (b'overdub', b'Overdub Media Activity')], default=b'discussion', max_length=100)),
                ('permission_control', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('read_after_post', models.BooleanField(default=False)),
                ('private_mode', models.BooleanField(default=False)),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='discussions', to='core.ActivityCollection')),
                ('lesson', models.ManyToManyField(blank=True, null=True, to='core.Lesson')),
                ('posts', models.ManyToManyField(blank=True, null=True, to='core.Post')),
            ],
            options={
                'abstract': False,
                'permissions': (('view_activity', 'view activity'),),
            },
        ),
    ]
