# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-11-01 00:48
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EssayActivity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('instructions', models.TextField()),
                ('display_order', models.IntegerField(default=0)),
                ('created', models.DateTimeField(auto_now_add=True, null=True)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('is_active', models.BooleanField(default=True)),
                ('activity_type', models.CharField(choices=[(b'discussion', b'Discussion Activity'), (b'essay', b'Essay Activity'), (b'overdub', b'Overdub Media Activity')], default=b'discussion', max_length=100)),
                ('permission_control', models.BooleanField(default=False)),
                ('is_deleted', models.BooleanField(default=False)),
                ('required_revisions', models.IntegerField(validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(50)])),
                ('collection', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='essays', to='core.ActivityCollection')),
                ('lesson', models.ManyToManyField(blank=True, null=True, to='core.Lesson')),
                ('posts', models.ManyToManyField(blank=True, null=True, to='core.Post')),
            ],
            options={
                'abstract': False,
                'permissions': (('view_activity', 'view activity'),),
            },
        ),
        migrations.CreateModel(
            name='EssayResponse',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('draft_title', models.CharField(default=b'default_draft_title', max_length=200)),
                ('draft_number', models.IntegerField(default=1)),
                ('status', models.CharField(default=b'in progress', max_length=100)),
                ('modified', models.DateTimeField(auto_now=True, null=True)),
                ('draft', models.TextField(blank=True, null=True)),
                ('review', models.TextField(blank=True, null=True)),
                ('flagged', models.BooleanField(default=False)),
                ('essay_activity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='essays.EssayActivity')),
                ('posts', models.ManyToManyField(blank=True, null=True, to='core.Post')),
                ('reviewed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='reviewed_essay_drafts', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='authored_essay_drafts', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
