# -*- coding: utf-8 -*-
# Generated by Django 1.9 on 2016-12-07 01:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayactivity',
            name='activity_type',
            field=models.CharField(choices=[(b'discussion', b'Discussion Activity'), (b'essay', b'Essay Activity'), (b'overdub', b'Overdub Media Activity'), (b'flatpage', b'Flatpage Activity')], default=b'discussion', max_length=100),
        ),
    ]
