# Generated by Django 2.1.3 on 2018-11-29 19:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('essays', '0002_auto_20161206_1547'),
    ]

    operations = [
        migrations.AlterField(
            model_name='essayactivity',
            name='activity_type',
            field=models.CharField(choices=[('discussion', 'Discussion Activity'), ('essay', 'Essay Activity'), ('overdub', 'Overdub Media Activity'), ('flatpage', 'Flatpage Activity')], default='discussion', max_length=100),
        ),
        migrations.AlterField(
            model_name='essayactivity',
            name='is_deleted',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='essayactivity',
            name='lesson',
            field=models.ManyToManyField(blank=True, to='core.Lesson'),
        ),
        migrations.AlterField(
            model_name='essayactivity',
            name='posts',
            field=models.ManyToManyField(blank=True, to='core.Post'),
        ),
        migrations.AlterField(
            model_name='essayresponse',
            name='draft_title',
            field=models.CharField(default='default_draft_title', max_length=200),
        ),
        migrations.AlterField(
            model_name='essayresponse',
            name='flagged',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='essayresponse',
            name='posts',
            field=models.ManyToManyField(blank=True, to='core.Post'),
        ),
        migrations.AlterField(
            model_name='essayresponse',
            name='status',
            field=models.CharField(default='in progress', max_length=100),
        ),
    ]
